before_script:
  - export MAINVERSION=$(grep -e '^version:' hasklepias-main/hasklepias-main.cabal | sed 's/version:[[:space:]]*//g')

variables:
  PKG: hasklepias 

stages:
  - pre-build
  # - build

docker-build:
 stage : pre-build
 image: docker:20.10.11
 script:
    - ./ci/ci-build-docker.sh $MAINVERSION Dockerfile

docker-build-musl:
 stage : pre-build
 image: docker:20.10.11
 script:
    - ./ci/ci-build-docker.sh $MAINVERSION nix/Dockerfile-static musl-haskell