# 
# NOTES
#
# * TODO: images in build steps use latest tag rather than the MAINVERSION variable
#   I believe this issue (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2793)
#   needs to be resolved in gitlab first.
#         

before_script:
  - export MAINVERSION=$(./scripts/get-version-from-cabal.sh hasklepias-main/hasklepias-main.cabal)

variables:
  MAINVERSION: $MAINVERSION
  PKG: hasklepias
  GHC: 8.10.7
  DOCKER: 20.10.11 

stages:
  - pre-build
  - build
  - docs
  - deploy

# Pre-build stage jobs #### 
docker-build:
 stage : pre-build
 image: docker:$DOCKER
 script:
    - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build haskell $GHC

docker-build-musl:
 stage : pre-build
 image: docker:$DOCKER
 script:
    - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build-musl musl-haskell $GHC

check-source:
  stage: pre-build
  image: registry.novisci.com/nsstat/statocker/haskell:$GHC
  script:
    - ./scripts/lint.sh
    - ./scripts/check-format.sh

# Build stage jobs #### 
build-test-hasklepias:
  stage: build
  needs: ["docker-build", "check-source"]
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build:${MAINVERSIOM}
  script:
    - cabal build all && cabal test all --test-show-details=always

build-cohort-collector-static:
  stage: build
  needs: ["docker-build-musl"]
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build-musl:latest
  artifacts :
    name: "${CI_PROJECT_NAME}-${SAFE_REF_NAME}"
    paths:
      - install/
    expire_in: 1 week
  script:
     - ./ci/ci-cabal-build-exe-static.sh cohort-collector cohort-collector install

# Docs jobs
check-docs:
  stage: docs
  needs: ["docker-build-musl"]
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build:latest
  script: 
    - ./ci/ci-docs-check.sh

# Deploy jobs
deploy-aws-cohort-collector-static:
  stage: deploy
  needs: ["build-cohort-collector-static"]
  image: registry.novisci.com/nsstat/statocker/aws
  script:
    - export BUNDLE=$(< install/cohort-collector.bundle)
    - | 
      aws s3 cp \
        install/${BUNDLE} \
        s3://$(< ci/downloads_path)${BUNDLE} \
        --acl public-read

deploy-docker-cohort-collector-static:
  stage: deploy
  needs: ["build-cohort-collector-static"]
  image: docker:$DOCKER
  script:
    - export NAME=$(cat install/cohort-collector.name)
    - export VERSION=$(cat install/cohort-collector.version)
    - echo "$NAME"
    - echo "$VERSION"
    - ./ci/ci-docker-build-cohort-collector.sh $VERSION install/$NAME
