# .gitlab-ci.yml 
#
# * The MAINVERSION variable defined in the build_vars job is the version of the 
#   hasklepias-main package. This version number is used to tag the docker images
#   used in the build pipeline. This variable is passed to child pipelines via 
#   the job's dotenv artifacts. 
# * See https://docs.gitlab.com/ee/ci/pipelines/parent_child_pipelines.html for
#   more information.

variables:
  PKG: hasklepias
  GHC: "8.10.7"
  DOCKER: "20.10.11"

stages:
  - prep
  - build

build_vars:
  stage: prep
  script:
    - echo "MAINVERSION=$(./scripts/get-version-from-cabal.sh hasklepias-main/hasklepias-main.cabal)" >> .env
  artifacts:
    reports:
      dotenv: .env

check-source:
  stage: prep
  image: registry.novisci.com/nsstat/statocker/haskell:$GHC
  script:
    - ./scripts/lint.sh
    - ./ci/ci-check-format.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

trigger-main-build:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes: ["**/*.hs", "**/*.cabal", "cabal.project"]
  stage: build
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger: 
    include: ci/ci-main-build.yml
    strategy: depend

trigger-static-build:
  stage: build
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger: 
    include: ci/ci-static-build.yml
    strategy: depend

