before_script:
  - export MAINVERSION=$(grep -e '^version:' hasklepias-main/hasklepias-main.cabal | sed 's/version:[[:space:]]*//g')

variables:
  PKG: hasklepias
  GHC: 8.10.7

stages:
  - pre-build
  # - build

docker-build:
 stage : pre-build
 image: docker:20.10.11
 script:
    - ./ci/ci-build-docker.sh $MAINVERSION ci/Dockerfile haskell $GHC

docker-build-musl:
 stage : pre-build
 image: docker:20.10.11
 script:
    - ./ci/ci-build-docker.sh $MAINVERSION ci/Dockerfile musl-haskell $GHC