# 
# NOTES
#
# * TODO: https://gitlab.novisci.com/nsStat/asclepias/-/issues/139 
# * https://docs.gitlab.com/ee/ci/yaml/#needspipelinejob   

variables:
  PKG: hasklepias
  GHC: "8.10.7"
  DOCKER: "20.10.11" 

stages:
  - prep
  - pre-build
  # - docs

build_vars:
  stage: prep
  script:
    - echo "MAINVERSION=$(./scripts/get-version-from-cabal.sh hasklepias-main/hasklepias-main.cabal)" >> .env
  artifacts:
    reports:
      dotenv: .env

check-source:
  stage: prep
  image: registry.novisci.com/nsstat/statocker/haskell:$GHC
  script:
    - ./scripts/lint.sh
    - ./ci/ci-check-format.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

trigger-main-build:
  stage: pre-build
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger: 
    include: ci/ci-main-build.yml
    strategy: depend

trigger-static-build:
  stage: pre-build
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger: 
    include: ci/ci-static-build.yml
    strategy: depend

