# 
# NOTES
#
# * TODO: images in build steps use latest tag rather than the MAINVERSION variable
#   I believe this issue (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2793)
#   needs to be resolved in gitlab first.
#         

before_script:
  - export MAINVERSION=$(grep -e '^version:' hasklepias-main/hasklepias-main.cabal | sed 's/version:[[:space:]]*//g')

variables:
  PKG: hasklepias
  GHC: 8.10.7

stages:
  - pre-build
  - build
  - install 

# Pre-build stage jobs #### 
docker-build:
 stage : pre-build
 image: docker:20.10.11
 script:
    - ./ci/ci-build-docker.sh $MAINVERSION hasklepias-build haskell $GHC

docker-build-musl:
 stage : pre-build
 image: docker:20.10.11
 script:
    - ./ci/ci-build-docker.sh $MAINVERSION hasklepias-build-musl musl-haskell $GHC

check-source:
  stage: pre-build
  image: registry.novisci.com/nsstat/statocker/haskell:$GHC
  script:
    - ./scripts/lint.sh
    - ./scripts/check_format.sh

# Build stage jobs #### 
build-test-hasklepias:
  stage: build
  needs: ["docker-build", "check-source"]
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build:latest
  script:
    - cabal build all && cabal test all

# Install stage jobs ####

install-cohort-collector:
  stage: build
  needs: ["docker-build-musl", "build-test-hasklepias"]
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build-musl:latest
  # cache:
  #   key: "$CI_JOB_NAME"
  #   paths:
  #     # - dist-newstyle/
  #     - install/
  #     # - cohort-collector*
  # artifacts :
  #   name: "${CI_PROJECT_NAME}-${SAFE_REF_NAME}"
  #   paths:
  #     - "cohort-collector*.tar.gz"
  #   expire_in: 1 week
  script:
     - ./ci/ci-build-install-exe-static.sh cohort-collector cohort-collector install/
#   # release:
#   #   name: 'Release $TAG'
#   #   description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION and the $TAG
#   #   tag_name: '$TAG'                                                 # variables must be defined elsewhere
#   #   ref: '$CI_COMMIT_SHA'                                            # in the pipeline. For example, in the
#   #   assets:
#   #     links:
#   #       - name: 'asset1'
#   #         url: 'https://download.novisci.com/hasklepias/collector-$VERSION-linux-$CI_RUNNER_EXECUTABLE_ARCH.tar.gz'