# 
# NOTES
#
# * TODO: https://gitlab.novisci.com/nsStat/asclepias/-/issues/139 
#         
create-artifact:
  stage: build
  script: echo "sample artifact" > artifact.txt
  artifacts:
    paths: [artifact.txt]

child-pipeline:
  stage: test
  trigger:
    include: ci/ci-static-build.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID