image: registry.novisci.com/nsstat/statocker/haskell:8.10.4

before_script:
  - export VERSION=$(grep -e '^version:' hasklepias.cabal | sed 's/version:[[:space:]]*//g')
  - export NAME=$(grep -e '^name:' hasklepias.cabal | sed 's/name:[[:space:]]*//g')

variables:
  PKG: hasklepias 

stages:
  - docker
  - build

docker-build:
 stage : docker
 image: docker:19.03.8
 script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin  $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE/$PKG-build:$VERSION --tag $CI_REGISTRY_IMAGE/$PKG-build:latest .
    - docker push $CI_REGISTRY_IMAGE/$PKG-build:$VERSION
    - docker push $CI_REGISTRY_IMAGE/$PKG-build:latest

build:
  stage: build
  # NOTE: I couldn't get the $VERSION variable to work as in:
  #  image : registry.novisci.com/nsstat/asclepias/$PKG-build:$VERSION
  # hence, using latest tag, but this may not be ideal
  image: registry.novisci.com/nsstat/asclepias/$PKG-build:latest
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - dist-newstyle/
  script:
    - ghc --version
    - cabal --version
    - cabal build

test:
  stage: build
  # NOTE: I couldn't get the $VERSION variable to work as in:
  #  image : registry.novisci.com/nsstat/asclepias/$PKG-build:$VERSION
  # hence, using latest tag, but this may not be ideal
  image: registry.novisci.com/nsstat/asclepias/$PKG-build:latest
  cache:
    # https://cabal.readthedocs.io/en/3.4/nix-local-build.html?highlight=dist-newstyle#caching
    key: "$CI_JOB_NAME"
    paths:
      - dist-newstyle/
  script:
    - ghc --version
    - cabal --version
    - cabal test --test-show-details=always 


