# .gitlab-ci.yml 
#
# * The MAINVERSION variable defined in the build_vars job is the version of the 
#   hasklepias-main package. This version number is used to tag the docker images
#   used in the build pipeline. This variable is passed to child pipelines via 
#   the job's dotenv artifacts. 
# * See https://docs.gitlab.com/ee/ci/pipelines/parent_child_pipelines.html for
#   more information.

variables:
  PKG: hasklepias
  GHC: "9.2.2"
  DOCKER: "20.10.11"

# Tag all jobs with nsstat so that the nsstat runner is used:
# https://gitlab.com/groups/TargetRWE/epistats/-/runners/16673355
default: 
  tags: ["nsstat"]

stages:
  - prep
  - build
  - deploy

build_vars:
  stage: prep
  script:
    - echo "MAINVERSION=$(./scripts/get-version-from-cabal.sh hasklepias-main/hasklepias-main.cabal)" >> .env
  artifacts:
    reports:
      dotenv: .env

# rule evaluating to true only if commit branch is default (master) and a
# version tag is pushed. 
.rules-version-tag-master:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /v.+/'

check-source:
  stage: prep
  image: registry.gitlab.com/targetrwe/epistats/nsstat/nsbuild/haskell:$GHC
  script:
    - ./scripts/lint.sh
      #    TODO
      #    https://gitlab.com/TargetRWE/epistats/nsstat/asclepias/-/issues/334
      #    - ./ci/ci-check-format.sh

trigger-main-build:
  stage: build
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    PARENT_CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
  trigger: 
    include: ci/ci-main-build.yml
    strategy: depend

# Trigger the downstream noviverse site to build *only* if a tag is pushed with
# name v* (version tag)
trigger-doc-site:
  stage: build
  rules:
    - !reference [.rules-version-tag-master, rules]
  trigger: nsStat/noviverse-site

# # Report the test coverage as described in the following links. If the pipeline
# # succeeds, the coverage is shown in the merge request widget and in the jobs
# # table. The coverage is expected to written as an artifact to
# # `coverage-report.txt` in the form produced by Hpc.
# # * https://gitlab.com/help/ci/pipelines/settings#test-coverage-parsing
# # * https://docs.gitlab.com/13.12/ee/ci/yaml/README.html#coverage
# coverage-report:
#   stage: coverage
#   image: docker:$DOCKER
#   coverage: '/\d+\% top-level/'
#   script:
#     - cat coverage-report.txt

