:navtitle: Event Data Theory
:description: Explanation and details of Event data theory
:source-highlighter: highlightjs
:toc: auto
// TODO: update edm-path to non-sandbox URL
:edm-path: https://docs.novisci.com/edm-sandbox/latest
:lawvere-url: https://bartoszmilewski.com/2017/08/26/lawvere-theories/

= Event Data Theory
`asclepias` provides the types and functions
for defining *models* of event data.
The terms "theory" and "model" are borrowed from the notion of a
{lawvere-url}[Lawvere theory].
footnote:lawvere[
We use the terms informally
to give the sense that a model of events is an instance of the theory.
We have not checked that the event data theory
actually is a universal algebra.
]

== Definitions
=== Event

include::theory:define-event.adoc[]

=== Context

include::theory:define-context.adoc[]

=== Tags

include::theory:define-tagset.adoc[]

=== Facts and Model
See the `event-data-model` documentation for a definition of xref:event-data:models:page$define-facts.adoc[`Facts`] and  xref:event-data:models:page$define-models.adoc[`Model`]. Note that `Fact` and `Model` defined there are types defined in the Dhall programming language. The programmer using `asclepias` must manually define in Haskell code a type `m` within the `Context c m` that corresponds to the `Model` for a given project.

=== Source
The `Source` type stores information on the origins of the data.
This allows for increased traceability of the data from source to final analysis.


A `Source` type has the following definition:

[source,haskell]
---
data Source = MkSource
  { column   :: Maybe T.Text
  , file     :: Maybe T.Text
  , row      :: Maybe Integer
  , table    :: T.Text
  , database :: T.Text
  }
  deriving (Eq, Show, Generic)
---

`column` is the column name of the source data.
`file` is the path of the source data.
`row` is the row number of the source data.
`table` is the name of the source data table.
`database` refers to the name of the data source.
For example "Optum" or "Medicaid"

=== Example
Here is an example of an `Event`:

[source,haskell]
----
include::ROOT:example$EventDataTheory/TheoryTest.hs[tag=exampleEvent]
----

The `+SillyEvent+` type is a project-specific synonym for an `Event` where
the `TagSet` is `Text`.

`SillySchema` is the `Model`, a Haskell sum type, with a different `Fact` given by each of its possible value types

and the `Interval` type is any valid type `a`, such as `Int`.

This structure provides a high degree of flexibility in defining new structures for study-specific cohort definitions and analysis.

See the
{edm-path}/index.html[`event-data-theory`]
documentation for details.






