:navtitle: Event Data Theory
:description: Explanation and details of Event data theory
:source-highlighter: highlightjs
:toc: auto

= Event Data Theory
`asclepias` provides the types and functions for defining *models* of event
data. The types and terminology are intended to be consistent with the
xref:event-data-model:ROOT:index.adoc[`event-data-model`] project.

== Definitions
=== Event

include::theory:define-event.adoc[]

=== Context

include::theory:define-context.adoc[]

=== Tags

include::theory:define-tagset.adoc[]

=== Facts and Model
See the `event-data-model` documentation for a definition of xref:event-data-model:theory:page$introduction.adoc#_what_is_a_fact[`Facts`] and  xref:event-data-model:theory:page$introduction.adoc#_what_is_a_model[`Model`]. Note that `Fact` and `Model` defined there are types defined in the Dhall programming language. The programmer using `asclepias` must manually define in Haskell code a type `m` within the `Context c m` that corresponds to the `Model` for a given project.

=== Source
The `Source` type stores information on the origins of the data.
This allows for increased traceability of the data from source to final analysis.


A `Source` type has the following definition:

[source,haskell]
---
data Source = MkSource
  { column   :: Maybe T.Text
  , file     :: Maybe T.Text
  , row      :: Maybe Integer
  , table    :: T.Text
  , database :: T.Text
  }
  deriving (Eq, Show, Generic)
---

`column` is the column name of the source data.
`file` is the path of the source data.
`row` is the row number of the source data.
`table` is the name of the source data table.
`database` refers to the name of the data source.
For example "Optum" or "Medicaid"

=== Example
Here is an example of an `Event`:

[source,haskell]
----
include::ROOT:example$EventDataTheory/TheoryTest.hs[tag=exampleEvent]
----

The `+SillyEvent+` type is a project-specific synonym for an `Event` where
the `TagSet` is `Text`.

`SillySchema` is the `Model`, a Haskell sum type, with a different `Fact` given by each of its possible value types

and the `Interval` type is any valid type `a`, such as `Int`.

This structure provides a high degree of flexibility in defining new structures for study-specific cohort definitions and analysis.

See the
xref:event-data-model:ROOT:index.adoc[`event-data-model`]
documentation for details.






