:navtitle: Event Data Theory
:description: Explanation and details of Event data theory
:source-highlighter: highlightjs
:toc: auto
:interval-algebra-v: 1.3.0
// TODO: update edm-path to non-sandbox URL
:edm-path: https://docs.novisci.com/edm-sandbox/latest
:lawvere-url: https://bartoszmilewski.com/2017/08/26/lawvere-theories/

= Event Data Theory
`asclepias` provides the types and functions
for defining *models* of event data.
The terms "theory" and "model" are borrowed from the notion of a
{lawvere-url}[Lawvere theory].
footnote:lawvere[
We use the terms informally
to give the sense that a model of events is an instance of the theory.
We have not checked that the event data theory
actually is a universal algebra.
]

== Definitions
=== Event

include::theory:define-event.adoc[]

=== Context

include::theory:define-context.adoc[]

=== Tags

include::theory:define-tagset.adoc[]

=== Facts and Model
See the `event-data-model` documentation for a definition of xref:event-data-model:models:page$define-facts.adoc[`Facts`] and  xref:event-data-model:models:page$define-models.adoc[`Model`]. Note that `Fact` and `Model` defined there are types defined in the Dhall programming language. The programmer using `asclepias` must manually define in Haskell code a type `m` within the `Context c m` that corresponds to the `Model` for a given project.

=== Example
Here is an example of an `Event`:

[source,haskell]
----
include::ROOT:example$EventDataTheory/TheoryTest.hs[tag=exampleEvent]
----

The `+SillyEvent+` type is a project-specific synonym for an `Event` where
the `TagSet` is `Text`.

`SillySchema` is the `Model`, a Haskell sum type, with a different `Fact` given by each of its possible value types

and the `Interval` type is any valid type `a`, such as `Int`.

This structure provides a high degree of flexibility in defining new structures for study-specific cohort definitions and analysis.

See the
{edm-path}/index.html[`event-data-theory`]
documentation for details.






