:description: Documentation for buildNofXBase template

The `buildNofXBase` template is generally used a basis for creating new templates that follow the pattern:

1. Filter events to those satisfying two conditions:
  * an interval relation with an assessment interval
  * a provided predicate function such as containing certain concepts
2. Preprocess these events.
3. Process the events.
4. Post-process the events, optionally in conjunction with the assessment interval

== Usage

The `exampleBuilder` function returns another feature builder that performs this logic:

1. combines the intervals of the input events (collapsing concurring and meeting intervals)
2. gets the `end` of each interval
3. computes the difference from each `end` to the `begin` of the assessment interval.


To be fully specified as a `Definition` and used in a project, the `exampleBuilder` function needs 3 additional inputs:

1. a function mapping the index interval to an assessment interval.
2. a predicate function comparing events to the assessment interval.
3. another predicate function on the events.

For example, the `buildExampleBaselineEnrollment` is a `Definition` that performs the logic of `buildExample` on enrollment events concurring with baseline, where baseline is defined as 180 days prior to index.

```haskell usage
buildExampleBaseline180Enrollment = 
  buildExample
     (makeBaselineFromIndex 180)
     concur
     isEnrollmentEvent
```