:sourceFile: DefineIndexSet.hs

= Defining an Index Set 

This example demonstrates:

* [x] how to create an index set

In this example,
index is defined as the first time that a subject was bitten by an Orca
(ICD10 codes W56.21/W56.21XA).

[source,haskell]
----
include::{sourcefile}[tag=function]
----

<1> The input type for this example is a list of events, 
where the concepts are `Text`, 
the data model is `ExampleModel`,
and the interval time is a generic type `a`.
<2> The return type is an `Indexset` of `Interval`.
The `IndexSet` type is defined in `hasklepias-core`
as `Maybe` a non-empty set of ordered values. 
That is, an `IndexSet` is either `Nothing` or 
a set of *unique* ordered values 
(in this case `Interval` values).
In practice, this means that a subject can have 0 or more indices.
<3> To determine whether a subject has an index,
we first filter to the events tagged with the concept `"wasBitByOrca"`.
<4> The `headMay` function gets the first event,
if one exists.
We're assuming the input list has already been sorted here.
<5> Then we get the interval, 
if it exists.
<6> The `into` function simply casts the `Maybe (Interval a)`
that the last step returned into an `IndexSet (Interval a)`

