= Create a cohort with calendar-based indices

This examples demonstrates:

* [x] specifying cohorts from calendar-based indices
* [x] using asclepias'
xref:page$theory.adoc[cohort module] without using its
xref:features:page$theory.adoc[feature module] 
* [x] using an empty return type for the cohort data
to just compute attrition information

[TIP]
Review the cohort building checklist 
#TODO: create such a document#

== Goal

Tha goal in this example is to create a cohort for each quarter of 2017.
The cohort should include subjects if
they have an enrollment event concurring with the first day of a quarter.
For this example, 


== Decide on the data model

In this example,
we use the following data model in our events: #TODO#



Here we create a type synonym for the the event type in this example
[source,haskell]
----
include::ExampleCalendarCohort.hs[tag=input]
----


== Create intervals for dates used for indices

[source,haskell]
----
include::ExampleCalendarCohort.hs[tag=indices]
----

== Define criteria

[source,haskell]
----
include::ExampleCalendarCohort.hs[tag=enrollPredicate]
----

Include the subject if she has an enrollment interval concurring with index.

[source,haskell]
----
include::ExampleCalendarCohort.hs[tag=enrolled]
----


== Write Cohort Specification

A cohort is #TODO: link to cohort definition#

Since the 

[source,haskell]
----
include::ExampleCalendarCohort.hs[tag=indexrunner]
----

[source,haskell]
----
include::ExampleCalendarCohort.hs[tag=criteriarunner]
----

[NOTE]
#TODO: we could have done this a different way#