
# Features, observational units, and Cohorts

## Features and Feature sets

A feature is a function that extracts a feature set $D$ from an event history $W$. Features are composed from the types of functions described above: accessors, predicates, filters, map/reduce functions, and basic arithmetic, set, and relational operators. Let $\mathcal{D}$ as the set of all possible information that could be extracted from $\mathcal{W}$.

\[
\mathsf{F}: \mathcal{W} \mapsto \mathcal{D}
\]

For example, let's define the "start of the first $\heartsuit$ after the start of the first $\spadesuit$". As a function of $W$, this can be expressed as

\[
\mathsf{F}^{\star}(W) = \min \{ \mathsf{a}_s(z) | z \in W' = \mathsf{L}^{\star}(W) \}
\]

where $\mathsf{L}^{\star}$ filters $W$ to the set of all $w$ that occur after the first $w$ with $\spadesuit$:

\[
\mathsf{L}^{\star}(W) = \{w | \mathsf{a}_s(c)  > \min(\mathsf{a}_s(s)), s \in S = \mathsf{L}(P^{\spadesuit}, W), c \in \mathsf{L}(P^{\heartsuit}, W)  \}
\]

\[
\mathsf{P}^{\text{suit}}(w) = \begin{cases}
1 & \mathsf{a}_t(w) = \text{suit} \\
0 & else
\end{cases}
\]

NOTE: to safely implement $F^{\star}$, we'll need to handle the empty set, $\emptyset$, but I'll ignore this for now.

Let's implement this in `R`:

```{r}
Amap_cast <- function(a){
  function(W){
    Map(a, W)
  }
}

Lsuit_cast <- function(suit){
  a_cast(c("context", "suit")) %>%
    p_cast(`==`, suit) %>%
    l_cast()
}

min_op <- function(A, L){
  force(A); force(L)
  function(w) {
    Reduce(min, A(L(w)))
  }
}

A_s    <- Amap_cast(a_s)
Lspade <- Lsuit_cast("spade")
Lheart <- Lsuit_cast("heart")

first_of <- function(what, filter){
  force(what); force(filter)
  function(w){
    min_op(what, filter)(w)
  }
}
  
first_start_of_spade <- first_of(A_s, Lspade)

fstar <- function(W){
  a_cast(c("interval", "a")) %>%
    p_cast(`>`, first_start_of_spade(W)) %>%
    l_cast() %>%
    { .(Lheart(W)) } %>%
    { first_of(A_s, Lheart)(.) }
}

fstar(W)
```

## Observational Unit

An observational unit is a context and a feature set:

$$
O = \{ \square, D \}
$$

## Cohort

Cohort is a context and a feature set.

$$
C = \{\square, \{O_1, \dots, O_{m^{\star}}\}\}
$$

