name:                hasklepias
version:             0.1.0
github:              "bsaul/hasklepias"
license:             BSD3
author:              "Bradley Saul"
maintainer:          "bsaul@novisci.com"
copyright:           "NoviSci, Inc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bsaul/hasklepias#readme>

dependencies:
- base >= 4.7 && < 5
- interval-algebra == 0.1.1
- aeson >= 1.4.0.0 && < 2
- containers >= 0.6.0
- unordered-containers >= 0.2.10
- text >= 1.2.3
- bytestring >= 0.10
- vector >= 0.12
- time >= 1.9

library:
  source-dirs: src

executables:
  hasklepias-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasklepias

tests:
  hasklepias-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasklepias
    - hspec
