:description: How to define the input data type

#TODO - I think we need instructions on how to tag things#
#I'm assuming that the tags will be in place already if using notionate?#

If using the Event type, define your project event as follows:

[source]
----
type YourEvent a = Event YourTags YourModel a
----

where

`a` is the temporal unit

`YourTags` is the type of your project's tags

`YourModel` is the type of your project's model

#TODO Do you need to have a tag type defined?#
#If so - can it be empty and what would that look like?#

If not using the Event type, define your input data type
base on your project's requirements.

In the example below,
the input data is a pair of values - one bool and one integer.

[source]
----
type InputData = (Bool, Integer)
----

Note that the subject identifier does not need to be defined.
When using `Event` data, 
the subject information is implicit in the structure.

When using non-`Event` data, 
the structure of the data still needs to meet certain requirements.
When parsed, the data must match the `Population d` type,
where `d` is the type of your input data.
The `Population` type can be interpreted as the subject identifier.
Any type that is coercible to a `String` can be used for `Population`.
If your project is using non-`Event` data,
contact the stats dev team for assistance.

The example below defines non-Event data.
The `Population` has type `Integer`.
The input data type `d` has type `MyInputData`,
which is equivalent to `(Bool, Integer)`.

[source,haskell]
----
examplePopulation :: Population MyInputData
examplePopulation =
  from @[(Integer, MyInputData)]
  [ (1, (False, 5))
  , (2, (True, 0))
  , (3, (False, 99))
  , (4, (False, -1))
  , (5, (True, -2))
  , (6, (False, 42))
  , (7, (True, 8))
  , (8, (True, 123))
  , (9, (False, 85))
  , (10, (True, 42))
  ]
----

Note `examplePopulation` is defined in code.
To use non-Event flat files,
additional structure will be needed.
Please reach out to the stats dev team for assistance.