:description: The procedure for creating an IndexSet 

An IndexSet represents the set of all index dates for an event.
asclepias requires a function defining how to create the IndexSet
from the input data in order to create a CohortSpec.

An IndexSet can always be made by applying the `makeIndexSet` function to a list.
Further, asclepias also defines an instance of `into`, 
which coerces a list into an IndexSet.
In fact, makeIndexSet is just a wrapper around `into`,
as seen below:

[source,haskell]
----
makeIndexSet :: (Ord i) => [i] -> IndexSet i
makeIndexSet = into
----

*Creating an empty IndexSet*

If no index is required for your project,
no function need be defined explicitly.
But, you could create a function like that below:
[source,haskell]
----
emptyIndex :: YourInputDataType -> IndexSet ()
emptyIndex _ = makeIndexSet [()]
----
Update `YourInputDataType` with your project-specific input data type.

Instead, you could also use `()` for the Index type when needed.

*Creating an IndexSet from an Event*

Define a function with type `[Event t m a] -> IndexSet (Interval a)`,
where `t` represents the project tags,
`m` represents the project model,
and `a` represents the type of the project's temporal unit

The following example index function takes in a list of `Event` s
and creates an `IndexSet` where the index is defined as
the last day that `YOUR_TAG` occurred for longer than 1 temporal unit (`a`)
during `yourStudyPeriod`.

*TODO - THIS EXAMPLE IS INCOMPLETE/INCORRECT AND WILL NOT COMPILE*
*https://gitlab.com/targetrwe/epistats/nsstat/asclepias/-/merge_requests/254#note_40892*
*https://gitlab.com/targetrwe/epistats/nsstat/asclepias/-/merge_requests/254#note_40893*
[source,haskell]
----
index :: [Event t m a] -> IndexSet (Interval a)
index events =
  events
    |> filterEvents (containsTag [YOUR_TAG])
    |> combineIntervals
    |> filter
         (getPredicate
           (Predicate ((> 1) . duration) &&& Predicate (concur yourStudyPeriod))
         )
    |> fmap (endervalMoment . end)
    |> into
----

*Creating an IndexSet from a list*

Define a function with type `YourInputDataType -> IndexSet (Interval a)`,
where `YourInputDataType` is the name of your input data type.

*TODO - what restrictions are there when not using Event type?*
*TODO finish instructions after getting more feedback on restrictions*




