:description: How to define the input data type

#TODO - I think we need instructions on how to tag things#
#I'm assuming that the tags will be in place already if using notionate?#
#Also If I tag the code with [source,haskell] it won't compile correctly#
#Is it something about type definitions?#

If using the Event type, define your project event as follows:

[source]
----
type YourEvent a = Event YourTags YourModel a
----
a is the temporal unit

YourTags is the type of your project's tags

YourModel is the type of your project's model

#TODO Do you need to have a tag type defined?#
#If so - can it be empty and what would that look like?#

If not using the Event type, define your input data type
base on your project's requirements.

In the example below,
the input data is a pair of values - one bool and one integer.
[source]
----
type InputData = (Bool, Integer)
----

Note that the subject identifier does not need to be defined.
#TODO - I'm still unclear how the subject identifier is created...#