:navtitle: Initialize new project
:description: How to initialize a new asclepias project

[IMPORTANT]
Replace `myProj` with your project ID 
wherever `myProj` or `<myProj>` appears in the instructions below.

. Initialize a git repo for your project,
using `nsProjects::initialize()` for example.
. In your terminal, navigate to the project folder.
. Execute the following commands in the terminal,
replacing `myProj` with your project name.
+
[source,shell]
----
PROJID=myProj
cabal init \
    --libandexe \
    --application-dir=apps \
    --source-dir=plans \
    --tests \
    --test-dir=tests \
    --package-name=$PROJID \
    --minimal \
    --homepage https://gitlab.novisci.com/nsResearch/$PROJID \
    --dependency hasklepias-main 
cabal update
mv plans/MyLib.hs plans/Cohorts.hs
mv tests/MyLibTest.hs tests/Main.hs
----
+
You may see warnings about fields in the `.cabal` file. 
You can safely ignore these.
. Update `<myProj>.cabal`
.. Change `exposed-modules` in the `library` stanza from `MyLib` to:
+
[source,config]
----
    exposed-modules: 
        Cohorts
      , Tests
----
.. Add the following section to the `library` stanza:
+
[source,config]
----
    default-extensions: 
      NoImplicitPrelude
      OverloadedStrings
      LambdaCase
      FlexibleContexts
      FlexibleInstances
      DeriveGeneric
      MultiParamTypeClasses
      DataKinds
      TypeApplications
----
.. Change `main-is` in the `test-suite` stanza to:
+
[source,config]
----
    main-is:          Main.hs
----
. Modify `plans/Cohorts.hs` to:
+
[source,haskell]
----
module Cohorts where

import Hasklepias
----
. Modify `apps/Main.hs` to:
+
[source,haskell]
----
module Main where

import  Cohorts

main :: IO ()
main = do
  putStrLn "Hello, Haskell!"
----
. Modify `tests/Main.hs` to:
+
[source,haskell]
----
import           Hasklepias
import           Tests

main :: IO ()
main = defaultMain (testGroup "<myProj> Tests" [tests])
----
. Add a file `Tests.hs` file in the `plans` directory with the following:
+
[source,haskell]
----
module Tests where

import           Hasklepias
import           Cohorts


tests :: TestTree
tests = testGroup "example" [testCase "true is true" (True @?= True) ]
----
. Add a `cabal.project` file in the project's root directory with the following, 
making sure to set the `tag` field to the commit hash
containing the version of `asclepias` to use:
+
----
source-repository-package
  type: git
  location: https://github.com/novisci/asclepias.git
  tag: <SET TO DESIRED COMMIT>
  subdir: hasklepias-core hasklepias-main event-data-theory

packages: ./<myProj>.cabal
----
. Add `dist-newstyle*` to `.gitignore`,
adding a `.gitignore` if necessary.
. Run `cabal build` to ensure the minimal project builds successfully.
