:description: instruction on how to install ghcup

= Installing ghcup

To install GHC and Cabal we recommend using 
https://www.haskell.org/ghcup[ghcup],
which is a utility for installing various applications in the Haskell toolchain.
Please see the linked documentation for instructions on how to launch the `ghcup` installer.

Once the installer is launched, you will be asked a series of questions.
The following is a rough guide to the recommended answers for these questions.

* _Do you want ghcup to automatically add the required PATH variable to your shell startup file?_
  This is optional. 
  Either (i) you should choose the "Yes, prepend" option
  and the installer will add a line of code
  to the end of your shell startup file (e.g. `$HOME/.bashrc`, `$HOME/.zshrc`, etc.)
  appropriately modifying the `PATH` environmental variable,
  or (ii) you should choose the "No" option
  and manually add some code to your shell startup file performing an equivalent modification to `PATH`.
  In the latter case you should prepend `$HOME/.cabal/bin` and `$HOME/.ghcup/bin` to `PATH`.
* _Do you want to install haskell-language-server (HLS)?_ 
  Select "Yes".
* _Do you want to install stack?_ 
  There is no harm in selecting "Yes",
  but it is not necessary for the asclepias project.
  So in other words, you can select "No" and download it at a later time if desired.

Once installed use `ghcup --help` to see a description of all the available commands.