:description: How to interactively code with Haskell
:source-highlighter: highlightjs
:ghc: 8.10.7
:ghc-docs: https://downloads.haskell.org/~ghc/{ghc}/docs/html/users_guide/

= Interactive usage of GHC

The GHC compiler provides an interactive environment 
(i.e. a read–eval–print loop or REPL) 
called GHCi 
(the "i" stands for "Interactive").
It can be very helpful to experiment with the REPL while writing Haskell code, 
much as you would with other programming languages like R or Python.
See 
{ghc-docs}ghci.html[Using GHCi] 
in the Cabal documentation for the full GHCi documentation.

== Starting GHCi in Cabal projects

To run GHCi in a Cabal project
you can use the `cabal repl` command
followed by an optional target package or package component
(if the component is not specified `cabal repl` loads the first component in a package).
There are many command-line arguments that can be provided with `cabal repl`, 
however for the sake of brevity these are not covered here.
See `cabal repl --help` and 
https://cabal.readthedocs.io/en/3.6/cabal-commands.html#cabal-v2-repl[cabal repl] 
in the Cabal documentation for full details.

The `cabal repl` command uses 
the same method of specifying a target package component as `cabal build` 
(see the <<Compiling asclepias packages>> section for details).
The following command will start GHCi 
and load the modules in the `examples` component of the `hasklepias-main` package
into the session 
(see the <<Loading modules into GHCi>> section for more detail on what "load" means).

[source,shell]
----
cabal repl hasklepias-main:examples
----

== Loading modules into GHCi

Loosely speaking, 
loading a module means that the declarations in the module are made known to GHCi.
Loading a module is a prerequisite 
to adding the module data and definitions 
to the GHCi top-level scope
(unless the module is part of a package known to GHCi).
To see what modules are loaded in a GHCi session at any given time 
you can use the command `:show modules` in the REPL.

When GHCi is invoked through `cabal repl`
all of the modules in the specified package component are loaded into GHCi.
If GHCi is invoked using the command `cabal repl hasklepias-main:examples`,
then the modules in the `examples` component of the `hasklepias-main` package
are loaded into the session.
Additionally,
if you want to change which modules are loaded during your session
then you can use the `:load` command in the REPL
to (i) load 0 or more specified modules 
and (ii) to forget all of the previously loaded modules.
It iss often more convenient to simply close the current GHCi session
and start a new session with the modules from a different package component loaded.

The following examples demonstrate how 
to view and change what modules are currently loaded.

[source,shell]
----
cabal repl hasklepias-main:examples
----
[source]
----
:show modules

:load ExampleCohort1
:show modules

:load ExampleCohort1 ExampleEvents
:show modules
----

For more details see the following documentation.

* https://cabal.readthedocs.io/en/3.6/cabal-package.html#opening-an-interpreter-session[Opening an interpreter session] 
in the Cabal documentation
* {ghc-docs}ghci.html#loading-source-files[Loading source files] 
in the GHC documentation
* {ghc-docs}ghci.html#ghci-cmd-:load[GHCi commands :load] 
in the GHC documentation
* {ghc-docs}ghci.html#module-and-load[:module and :load] 
in the GHC documentation

== Reloading updated modules in GHCi

When you update the source code for a given module or modules 
that have already been loaded and you want GHCi to recompile the program, 
you can use the `:reload` command.
See
{ghc-docs}ghci.html#ghci-cmd-:reload[GHCi commands :reload] 
in the GHC documentation for details.

== Managing scope in GHCi

GHCi provides support for fine-grained control over what top-level declaration
are available in the session (i.e. what is in scope).
The following subsections describe the various mechanisms
that can used to modify the scope.
See 
{ghc-docs}ghci.html#what-s-really-in-scope-at-the-prompt[What’s really in scope at the prompt?]
for full details.

=== Module import *-form in GHCi

When a given module is imported in GHCi 
(i.e. added to the current scope) 
it can be in one of two forms: 
the usual import form and a so-called *-form.
The regular form places the module exports in scope, 
whereas the *-form places all top-level bindings in the module in scope.

=== Viewing the current scope in GHCi

Use the command `:show imports` to list the modules that are currently in scope, 
and the command `:show bindings` to list any binding that were declared directly in the REPL.

In the following example,
we first start a new GHCi session and define the object `fib`.
The subsequent `:show bindings` command
then reports that the only binding made at the prompt was for `lib`.
Next we use `:module` command
to add several modules into the scope
(see the <<ghci-module-scope-control>> section for a description of `:module`).
Then a subsequent `:show imports` command provides the output shown below.
This can be read as meaning that
the exports from the `ExampleEvents` and `ExampleFeatures1` modules are in scope,
whereas the entirety of the `ExampleCohort1` and the `Main` modules are in scope
(i.e. they are *-form imports).

[source,shell]
----
cabal repl hasklepias-main:examples
----
[source]
----
fib = 1 : scanl (+) 1 fib
:show bindings
-- fib :: Num a => [a] = _

:module +*ExampleCohort1 ExampleEvents ExampleFeatures1
:show imports
-- :module +*ExampleCohort1
-- import ExampleEvents
-- import ExampleFeatures1
-- :module +*Main -- added automatically
----

=== How module loads affect scope in GHCi

When modules are loaded at GHCi startup 
(e.g. after invoking `cabal repl`)
or through the `:load` command
then a secondary effect of the load is
that an automatic import is added
to the scope for the most recently loaded target module.
The effect of this import is that
(i) the data and definitions of the module are made available to the top-level scope in GHCi, 
and (ii) all other bindings are removed from the top-level scope.

Note that the above effects also occur for the `:add` and `:reload` commands.
See 
{ghc-docs}ghci.html#the-effect-of-load-on-what-is-in-scope[The effect of :load on what is in scope] 
in the GHC documentation for more details.

=== Controlling what is in scope with the 'import' comand in GHCi 

You can use the usual Haskell `import` syntax
to add a module's exports 
(or possibly a subset of them) to the scope.
In the following example 
we sequentially add the exports from `ExampleFeatures1` and `ExampleFeatures1` to the scope,
but note that the effect is cumulative 
(i.e. each module is successively added to the scope).
See 
{ghc-docs}ghci.html#controlling-what-is-in-scope-with-import[Controlling what is in scope with import]
in the GHC documentation for full details.

[source,shell]
----
cabal repl hasklepias-main:examples
----
[source]
----
:show imports
-- :module +*Main -- added automatically

import ExampleFeatures1
:show imports
-- import ExampleFeatures1
-- :module +*Main -- added automatically

import ExampleEvents
:show imports
-- import ExampleFeatures1
-- import ExampleEvents
-- :module +*Main -- added automatically
----

=== Controlling what is in scope with the ':module' command in GHCi [[ghci-module-scope-control]]

An alternative to using an `import` command to modify the scope is
to use the `:module` command.
In the following example
we see three forms of the `:module` command: 
one with a `+` that adds module declarations to the current scope, 
one with a `-` that removes module declarations from the current scope, 
and one without either a `+` or a `-` which replaces the current scope with a new scope.
Furthermore,
each module that is imported by the `:module` command can be
either a regular import or a \*-form input by either omitting or including an `*` before each module name.
See {ghc-docs}ghci.html#controlling-what-is-in-scope-with-the-module-command[Controlling what is in scope with the :module command] in the GHC documentation for full details.

[source,shell]
----
cabal repl hasklepias-main:examples
----
[source]
----
:show imports
-- :module +*Main -- added automatically

:module + *ExampleCohort1 *ExampleEvents ExampleFeatures1 ExampleFeatures2
:show imports
-- :module +*ExampleCohort1
-- :module +*ExampleEvents
-- import ExampleFeatures1
-- import ExampleFeatures2
-- :module +*Main -- added automatically

:module - ExampleEvents ExampleFeatures2
:show imports
-- :module +*ExampleCohort1
-- import ExampleFeatures1
-- :module +*Main -- added automatically

:module *ExampleCohort1 *ExampleEvents
:show imports
-- :module +*ExampleCohort1
-- :module +*ExampleEvents
----
