:description: This file details how asclepias is versioned 
:toc: right 
:source-highlighter: highlightjs
:navtitle: Versioning
:antora-site: https://docs.antora.org/antora/latest

= Versioning `asclepias`

`asclepias` tries to follow
https://semver.org/[semantic versioning 2.0.0].

Each package in the `asclepias` project has the same version. Starting with
version `v0.27.0`, `asclepias` adheres to the
xref:nsBuild:usage-guides:page$git-usage.adoc[git usage guidelines]. In
particular, this means versions are marked with tagged commits on the projects
`origin/master` branch in GitLab, and work toward each release is tracked in
GitLab milestones. Version tags should be in the format `vx.x.x`, as in
`v0.27.0`.

[NOTE]
Version-changing edits to one package should bump the version in all packages.
As of `0.27.0`, version numbers should be of the form `x.x.x`, wherever they
are referenced or used, event if the final element is 0, meaning we write
`0.27.0` not `0.27`.  Where appropriate, references to version numbers will
start with `v` as they appear in the version-tagged commits, for example
`v0.27.0`. One place where a `v` prefix is not appropriate is in the package
`.cabal` files.

[TIP]
The `antora-playbook.yml` file in the
https://gitlab.com/targetrwe/epistats/nsstat/noviverse-site[`noviverse-site` repository]
determines which commit references of `asclepias` are used for the
documentation site. At present, these are the version-tagged commits beginning
with `v0.27.0`. The `docs/antora.yml` file of the `asclepias` repo sets the
version of this documentation based on the version tags.


[CAUTION]
Until `asclepias` version `1.0` is released,
no guarantees of backwards-compatability are made. 
