# The main build pipeline

stages:
  - prep
  - build
  - deploy
  - coverage

# The child pipeline needs at minimum one job to run - otherwise the sub-pipeline fails
# See https://gitlab.com/gitlab-org/gitlab/-/issues/218538
dummy:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - ":"

# Build the docker image with all dependencies installed.
docker-build:
  stage : prep
  image: docker:$DOCKER
  needs:
   - pipeline: $PARENT_PIPELINE_ID
     job: build_vars
     artifacts: true
  rules:
   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
     changes: ["**/*.cabal", "cabal.project"]
  script:
     - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build-musl haskell $GHC

main-build:
  stage: build
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - job: "docker-build"
      optional: true
  rules:
    - changes: ["**/*.cabal", "**/*.hs"]
    - if: '$CI_COMMIT_MESSAGE =~ /-build/'
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build:${MAINVERSION}
  script:
     - ./ci/ci-cabal-build-all.sh
  artifacts:
    paths:
      - install
      - coverage-report.txt
    expire_in: 1 hour

# Upload docs to S3
upload-haddock-docs:
  image: registry.novisci.com/nsstat/statocker/aws:latest
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - job: "main-build"
      optional: false
      artifacts: true
  rules:
    - changes: ["**/*.cabal", "**/*.hs"]
    - if: '$CI_COMMIT_MESSAGE =~ /-build/'
  stage: deploy
  script:
    - ./ci/ci-upload-docs-to-s3.sh

# Report the test coverage as described in the following links. If the pipeline
# succeeds, the coverage is shown in the merge request widget and in the jobs
# table.
# * https://gitlab.novisci.com/help/ci/pipelines/settings#test-coverage-parsing
# * https://docs.gitlab.com/13.12/ee/ci/yaml/README.html#coverage
coverage-report:
  stage: coverage
  image: docker:$DOCKER
  coverage: '\d+\% top-level'
    script:
      - cat coverage-report.txt
