# The main build pipeline 

stages:
  - pre-build
  - build 

# Build the docker image will all dependencies installed.
docker-build:
 stage : pre-build
 image: docker:$DOCKER
 needs:
  - pipeline: $PARENT_PIPELINE_ID
    job: build_vars
    artifacts: true
 rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    changes: ["**/*.cabal", "cabal.project"]
 script:
    - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build-musl haskell $GHC

build:
  stage: build
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - job: "docker-build"
      optional: true
  rules:
    - changes: ["**/*.hs"]
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build:${MAINVERSION}
  script:
     - ./ci/ci-cabal-build-all.sh
