# The main build pipeline 

stages:
  - pre-build
  - build 
  - deploy 

# The child pipeline needs at minimum one job to run - otherwise the sub-pipeline fails
# See https://gitlab.com/gitlab-org/gitlab/-/issues/218538
dummy:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - ":"

# Build the docker image will all dependencies installed.
docker-build:
 stage : pre-build
 image: docker:$DOCKER
 needs:
  - pipeline: $PARENT_PIPELINE_ID
    job: build_vars
    artifacts: true
 rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    changes: ["**/*.cabal", "cabal.project"]
 script:
    - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build-musl haskell $GHC

main-build:
  stage: build
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - job: "docker-build"
      optional: true
  rules:
    - changes: ["**/*.cabal", "**/*.hs"]
    - if: $CI_COMMIT_MESSAGE =~ /-do-main-build$/
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build:${MAINVERSION}
  script:
     - ./ci/ci-cabal-build-all.sh
  artifacts:
    paths:
      - install
    expire_in: 1 hour

upload: 
  image: registry.novisci.com/nsstat/statocker/aws:latest
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - job: "main-build"
      optional: false
  stage: deploy
  script:
    - ./ci/ci-upload-docs-to-s3.sh



