# The main build pipeline
stages:
  - prep
  - build
  # NOTE: See docs upload job
  #- deploy

# Tag all jobs with nsstat so that the nsstat runner is used:
# https://gitlab.com/groups/TargetRWE/epistats/-/runners/16673355
default: 
  tags: ["nsstat"]

# Rules for main-build and dependencies
.rules-main-build:
  rules:
    - if: '$PARENT_CI_COMMIT_BRANCH == $PARENT_CI_DEFAULT_BRANCH || $PARENT_CI_PIPELINE_SOURCE == "merge_request_event" || $PARENT_CI_PIPELINE_SOURCE == "push"'
      changes: ["**/*.cabal", "**/*.hs", "ci/ci-cabal-build-all.sh", "ci/ci-cabal-haddock-docs.sh", "ci/ci-docker-build.sh", "ci/dockerHasklepias"]
    - if: '$CI_COMMIT_MESSAGE =~ /-build/'
    - if: '$CI_COMMIT_MESSAGE =~ /-docker/'

# The child pipeline needs at minimum one job to run - otherwise the sub-pipeline fails
# See https://gitlab.com/gitlab-org/gitlab/-/issues/218538
dummy:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    # Print out some environmental variables for debugging information
    - 'echo "$CI_PIPELINE_SOURCE"'
    - 'echo "$CI_COMMIT_MESSAGE"'
    - 'echo "$PARENT_CI_PIPELINE_SOURCE"'
    - 'echo "$PARENT_PIPELINE_ID"'

# Build the docker image with all dependencies installed.
docker-build:
  stage : prep
  image: docker:$DOCKER
  needs:
   - pipeline: $PARENT_PIPELINE_ID
     job: build_vars
     artifacts: true
  rules:
    - !reference [.rules-main-build, rules]
  script:
     - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build haskell $GHC

main-build:
  stage: build
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - job: "docker-build"
      optional: true
  rules:
    - !reference [.rules-main-build, rules]
  image: registry.gitlab.com/targetrwe/epistats/nsstat/asclepias/hasklepias-build:${MAINVERSION}
  script:
     - ./ci/ci-cabal-build-all.sh

# Upload docs to S3
upload-haddock-docs:
  variables:
    ARTIFACT_DIR: "install/doc"
  image: registry.gitlab.com/targetrwe/epistats/nsstat/asclepias/hasklepias-build:${MAINVERSION}
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - job: "main-build"
      optional: false
      artifacts: true
  rules:
    # run only if the pipeline is a tag pipeline, and the tag begins with v.
    # intended to catch version tagged commits on master.
    # NOTE the matched expression is unrestrictive to avoid annoying no-builds
    # in case, e.g., we change our version numbering format.
    - if: '$CI_COMMIT_TAG !~ /^v/'
      when: never
    # if it does, run according to main-build rules
    - !reference [.rules-main-build, rules]

  stage: build
  # TODO: debug passing artifacts from one stage to another. check git blame to
  # see the MR where this was changed for background. in practice, version tags
  # will occur only on master, so it doesn't matter too much.
  #stage: deploy
  script:
    - ./ci/ci-cabal-haddock-docs.sh
    - ./ci/ci-upload-docs-to-s3.sh
