stages:
  - pre-build
  - build 
  - deploy

# Build the docker image will all dependencies installed.
docker-build-musl:
 stage : pre-build
 image: docker:$DOCKER
 needs:
  - pipeline: $PARENT_PIPELINE_ID
    job: build_vars
    artifacts: true
 script:
    - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build-musl musl-haskell $GHC

# Builds the cohort collector app
build-cohort-collector-static:
  stage: build
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - "docker-build-musl"
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build-musl:${MAINVERSION}
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - install/
    expire_in: 1 week
  script:
     - ./ci/ci-cabal-build-exe-static.sh cohort-collector cohort-collector install

# Deploy jobs
deploy-aws-cohort-collector-static:
  stage: deploy
  needs: ["build-cohort-collector-static"]
  image: registry.novisci.com/nsstat/statocker/aws
  script:
    - export BUNDLE=$(< install/cohort-collector.bundle)
    - | 
      aws s3 cp \
        install/${BUNDLE} \
        s3://$(< ci/downloads_path)${BUNDLE} \
        --acl public-read

deploy-docker-cohort-collector-static:
  stage: deploy
  needs: ["build-cohort-collector-static"]
  image: docker:$DOCKER
  script:
    - export NAME=$(cat install/cohort-collector.name)
    - export VERSION=$(cat install/cohort-collector.version)
    - ./ci/ci-docker-build-cohort-collector.sh $VERSION install/$NAME
