stages:
  - pre-build
  - build 

docker-build-musl:
 stage : pre-build
 image: docker:$DOCKER
 needs:
  - pipeline: $PARENT_PIPELINE_ID
    job: build_vars
    artifacts: true
 script:
    - ./ci/ci-docker-build.sh $MAINVERSION hasklepias-build-musl musl-haskell $GHC

build-cohort-collector-static:
  stage: build
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
    - "docker-build-musl"
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build-musl:${MAINVERSION}
  artifacts :
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - install/
    expire_in: 1 week
  script:
     - ./ci/ci-cabal-build-exe-static.sh cohort-collector cohort-collector install

