stages:
  - build 

use-artifact:
  stage: build
  script:
    - echo "$MAINVERSION" 
  # https://docs.gitlab.com/ee/ci/yaml/#needspipelinejob
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true

build-cohort-collector-static:
  stage: build
  # needs: ["docker-build-musl"]
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build_vars
      artifacts: true
  image: registry.novisci.com/nsstat/asclepias/hasklepias-build-musl:${MAINVERSION}
  artifacts :
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - install/
    expire_in: 1 week
  script:
     - ./ci/ci-cabal-build-exe-static.sh cohort-collector cohort-collector install

