
stages:
  - test 

# Pre-build stage jobs #### 
test:
 stage : test
 image: docker:$DOCKER
 needs:
  - job: build_vars
    artifacts: true
 script:
    - echo "I made it."
    - echo "$MAINVERSION" 

