= Development

To develop and work with asclepias locally, clone the repository:

----
git clone git@gitlab.novisci.com:nsStat/asclepias.git
----

== Installing GHC and cabal

To compile a Haskell library or application you will need a suitable compiler such as the https://www.haskell.org/ghc/[Glasgow Haskell Compiler] (GHC). Furthermore, to make the creation, distribution, and bulding of libraries and applications more convenient several systems and supporting tooling for defining Haskell packages have been created. In particular the asclepias project uses the https://www.haskell.org/cabal[cabal] system for building and packaging Haskell libraries and programs so it will be helpful to have the cabal application available on your development platform.

=== Installing ghcup

To install GHC and cabal we recommend using the https://www.haskell.org/ghcup[ghcup utility]. Please see the linked documentation for installation instructions.

=== Installing GHC and cabal using ghcup

ghcup is a utility that allows for easy downloading and installation of various Haskell-related applications such as GHC and cabal, among others. You can use the command `ghcup list` to provide a table of all of the available applications versions that can be installed through ghcup. Use `ghcup --help` to see a description of all of the available commands.

To install an application you can use a command such as `ghcup install ghc 8.10.7`. Supplying the version number is optional, and if not supplied then ghcup will install what it considers to be the recommended version. To see which version of a given application that ghcup considers to be recommended, you can use `ghcup list`. Use `ghcup install --help` for documentation.

We recommend installing the recommended version of cabal according to ghcup, and the version of GHC used in the `.gitlab-ci.yml` file (see the `GHC` variable defined therein). So in summary, this means that you can run the following commands.
[source,shell]
----
ghcup upgrade
ghcup install ghc 8.10.7  # double-check to make sure this is current
ghcup install cabal
----

==== ghcup troubleshooting: SSL certificate problem

Some users on our team (as of January 2022) have reported difficulties when using ghcup where they encounter an error with a message like the following.
[literal]
curl: (60) SSL certificate problem: self signed certificate in certificate chain

Below we list a few workarounds that we have found for this issue.
* Update your OpenSSL certificates. If you installed OpenSSL on macOS through homebrew then you can use the command `brew postinstall openssl`.
* Upgrade the version of curl. If you run `curl --version` and it lists an old release date then you may want to install a newer version.
* Use wget instead of curl when running ghcup by specifying the option `--downloader=wget`. So for example, you can use the command `ghcup --downloader=wget list`

==== A note on the cabal version

As you find your way around the asclepias project, you may notice that in the sub-project cabal configuration files (i.e. the files with filenames ending in `.cabal`), that the `cabal-version` is specified as an older version of cabal (such as version 2.2) than can be downloaded through ghcup. According to https://cabal.readthedocs.io/en/3.6/cabal-package.html#pkg-field-cabal-version[the cabal documentation] cabal is mostly backwards compatible so there shouldn't be any issue with using a newer version.

==== A note on the GHC version and language extensions

As you find your way around the asclepias project, you may notice that in the sub-project cabal configuration files (i.e. the files with filenames ending in `.cabal`) that the `default-language` is specified as `Haskell2010`, which refers to the https://www.haskell.org/onlinereport/haskell2010/(Haskell 2010 language report), and is the current definition of the Haskell language (also see https://en.wikipedia.org/wiki/Haskell_(programming_language)#Haskell_2010(Wikipedia) and https://wiki.haskell.org/Language_and_library_specification#The_Haskell_2010_report(The Haskell Wiki)). GHC versions 8.0.2 and later implement the Haskell 2010 language report.

Although the Haskell language definition itself has stayed stable since the Haskell 2010 language report, the GHC compiler supports the adoption of new language features through the use of _language extensions_, which are opt-in non-standard language features. One of the effects of the specifying the Haskell 2010 language is that the language extensions listed https://downloads.haskell.org/~ghc/8.10.7/docs/html/users_guide/glasgow_exts.html#extension-Haskell2010(in this link) are enabled by GHC.

Additional language extensions can be (and typically are) specified by various mechanisms in the sub-project cabal configuration files or in the modules (i.e. source code files) themselves  https://kowainik.github.io/posts/extensions(as described here).

== Setting up a development environment

=== Installing an editor

Haskell development is well-supported by many popular editors such as https://code.visualstudio.com[Visual Studio Code], https://www.sublimetext.com/[Sublime Text], https://www.vim.org/[vim]/https://neovim.io/[Neovim], https://atom.io/[Atom], https://www.gnu.org/software/emacs/[Emacs], and others. If you do not have a preexisting preference of editor then we recommend using Visual Studio Code to get started.

To see installation instructions for a given editor listed above, please visit the corresponding provided link. Note however that in the case of Emacs it is fairly common to use an Emacs distribution to reduce the effort required to set up Emacs (basically a collection of packages bundled with base Emacs) such as https://www.spacemacs.org/[Spacemacs], https://github.com/hlissner/doom-emacs[Doom Emacs], https://prelude.emacsredux.com/en/latest/[Emacs Prelude], and https://github.com/purcell/emacs.d[Purcell Emacs].

=== Installing the Haskell Language Server

The https://github.com/haskell/haskell-language-server[Haskell language server] (HLS) implements the Language Server Protocol[https://microsoft.github.io/language-server-protocol/] (LSP) for the Haskell language. It can be very useful for development when paired with an editor with support for LSP (such as one of the editors mentioned above) since it provides immediate feedback from the compiler, among other features.

You can use ghcup to install whatever its current recommended version of HLS is.
[source,shell]
----
ghcup upgrade
ghcup install hls
----

=== Configuring your editor to utilize HLS

Please see  https://haskell-language-server.readthedocs.io/en/latest/configuration.html#configuring-your-editor[the HLS documentation] for instructions on how to configure your editor to utilize HLS.

==== A note on using HLS in multi-project repositories

Since the asclepias repository has a multiple project layout, it may not be obvious how to configure HLS. For example, should you run one server that serves all of the files across the various projects, or should you run one server per project?

To resolve this issue, the asclepias repository provides a file `hie.yaml` in the repository root that specifies the HLS configuration for all of the projects in the repository (see the https://github.com/haskell/hie-bios[hie-bios documentation] for details). As a result of this setup, you can run a single HLS server that will work correctly for all of the projects in the repository. If you are asked by your editor to specify what directory to start HLS in then you can use the repository root directory.

Note that some editors may automatically detect the hie-bios configuration setup in the repository and just "do the right thing." If you open a Haskell file in your editor and LSP seems to be working properly then you are probably good-to-go.

==== Troubleshooting HLS

If HLS ever stops working, you may need to clear the cache:

[source,shell]
----
rm -rf ~/.cache/hie-bios/dist-asclepias*
----

== Interactive Usage

To run the examples interactively, open a ghci session with:

[source,shell]
----
cabal repl hasklepias:examples 
----

In ghci you have access to all exposed functions in hasklepias, interval-algebra, and those in the examples folder.


== Linting and Formatting

The CI process checks that code in the repository is appropriately formatted and linted, using the https://hackage.haskell.org/package/brittany[`brittany`] and  https://github.com/ndmitchell/hlint[`hlint`] tools respectively. 

You can install these locally using (e.g.) `cabal`:

[source,shell]
----
cabal install brittany
cabal install hlint
----

Scripts are provided to format code locally with:

[source,shell]
----
./scripts/format.sh
----

or linted using: 

[source,shell]
----
./scripts/lint.sh
----

