= Development

To develop and work with asclepias locally, clone the repository:

----
git clone git@gitlab.novisci.com:nsStat/asclepias.git
----

== Installing GHC and cabal

To compile Haskell libraries and/or applications you will need a suitable Haskell compiler. Furthermore, to make the creation, distribution, and bulding of libraries and applications more convenient several systems and supporting tooling for defining Haskell packages have been created. In particular, the asclepias project uses the https://www.haskell.org/ghc/[Glasgow Haskell Compiler (GHC)] compiler and the https://www.haskell.org/cabal[cabal] system for building and packaging Haskell libraries and programs so consequently it will be helpful to have GHC and cabal available on your development platform.

=== Installing ghcup

ghcup is a utility that allows for easy downloading and installation of various applications in the Haskell toolchain such as GHC and cabal, among others. To install GHC and cabal we recommend using the https://www.haskell.org/ghcup[ghcup utility]. Please see the linked documentation for instructions to lauch the installer.

Once the installer is launched, you will be asked a series of questions. The following is a rough guide to the recommended answers for these questions.

* _Do you want ghcup to automatically add the required PATH variable to your shell startup file?_ This is optional. Either (i) you should choose the "Yes, prepend" option and the installer will add a line of code to the end of your shell startup file (e.g. `~/.bashrc`) appropriately modifying the `PATH` environmental variable, or (ii) you should choose the "No" option and manually add some code to your shell startup file performing an equivalent modification to `PATH`. In the latter case you should prepend `~/.cabal/bin` and `~/.ghcup/bin` to `PATH`.
* _Do you want to install haskell-language-server (HLS)?_ Select "Yes".
* _Do you want to install stack?_ There is no harm in selecting "Yes", but it is not necessary for the asclepias project. So in other words, you can select "No" and download it at a later time if desired.

Once installed use `ghcup --help` to see a description of all the available commands.

==== ghcup troubleshooting: SSL certificate problem

Some users on our team (as of January 2022) have reported difficulties when using ghcup where they encounter an error with a message like the following.
[literal]
curl: (60) SSL certificate problem: self signed certificate in certificate chain

Below we list a few workarounds that we have found for this issue.

* Update your OpenSSL certificates. If you installed OpenSSL on macOS through homebrew then you can use the command `brew postinstall openssl`.
* Upgrade the version of curl. If you run `curl --version` and it lists an old release date then you may want to install a newer version.
* Use wget instead of curl when running ghcup by specifying the option `--downloader=wget`. So for example, you can use the command `ghcup --downloader=wget list`

==== Obtaining the ghcup facilities information

Use the command `ghcup list` to orient yourself with the following information.

1. What applications and application versions are available for download through ghcup.
2. What applications have already been downloaded through ghcup.
3. What the current recommended version of an application is according to ghcup.
4. What version of a given application "is active" (see the <<ghcup application version management>> section for details on what is meant by "is active").

The first column of the table provided by `ghcup list` is the least obvious. If a given row has an "✗", then it means that the corresponding version of the application _hasn't_ been downloaded by ghcup. If it has a "✔", then it means that it _has_ been downloaded by ghcup, and if it has a "✔✔" then it means that it both _has_ been downloaded by ghcup _and is_ the currently active version.

==== ghcup application version management

ghcup stores various application versions in the `~/.ghcup/bin` directory, and which is assumed to be on your shell's path. Then for example, the `ghc` file located in that directory is a symbolic link to the active version of GHC according to ghcup (a similar pattern is used for other applications managed by ghcup). So suppose that the active version of GHC was GHC 8.10.7, then running the command `ghc` in your shell would run GHC 8.10.7. If however you wanted to run a different version of GHC, say GHC 9.2.1, for a particular project without changing the active version, then you could invoke that version directly by running the command `ghc-9.2.1` in your shell since this is one of the files in `~/.ghcup/bin` (assuming that it has previously been downloaded).

To change the currently active version for a particular application, use the `ghcup set` command. See `ghcup set --help` for details.

=== Installing GHC and cabal using ghcup

To install an application you can use a command such as `ghcup install ghc 8.10.7`. Supplying the version number is optional, and if not supplied then ghcup will install what it considers to be the recommended version. To see which version of a given application that ghcup considers to be recommended, you can use `ghcup list` as described in the <<Obtaining the ghcup facilities information>> section. Use `ghcup install --help` for documentation.

We recommend installing the recommended version of cabal according to ghcup, and the version of GHC used in the `.gitlab-ci.yml` file (see the `GHC` variable defined therein). So in summary, this means that you can run the following commands. Note that you may already have the necessary versions of GHC and cabal installed in which case either or both of these commands can be omitted as appropriate (however there is no harm in running them in any case since ghcup is smart enough to not download an existing application a second time).
[source,shell]
----
ghcup install ghc 8.10.7  # double-check to ensure this is the correct version
ghcup install cabal
----

If you already have GHC and/or cabal installed through ghcup and you need to change the version then you can use the `ghcup set` command.

==== A note on the cabal version

As you find your way around the asclepias project, you may notice that in the sub-project cabal configuration files (i.e. the files with filenames ending in `.cabal`), that the `cabal-version` is specified as an older version of cabal (such as version 2.2) than can be downloaded through ghcup. According to https://cabal.readthedocs.io/en/3.6/cabal-package.html#pkg-field-cabal-version[the cabal documentation] cabal is mostly backwards compatible so there shouldn't be any issue with using a newer version.

==== A note on the GHC version and language extensions

As you find your way around the asclepias project, you may notice that in the sub-project cabal configuration files (i.e. the files with filenames ending in `.cabal`) that the `default-language` is specified as `Haskell2010`, which refers to the https://www.haskell.org/onlinereport/haskell2010/[Haskell 2010 language report], and is the current definition of the Haskell language (also see https://en.wikipedia.org/wiki/Haskell_(programming_language)#Haskell_2010[Wikipedia] and https://wiki.haskell.org/Language_and_library_specification#The_Haskell_2010_report[The Haskell Wiki]). GHC versions 8.0.2 and later implement the Haskell 2010 language report.

Although the Haskell language definition itself has stayed stable since the Haskell 2010 language report, the GHC compiler supports the adoption of new language features through the use of _language extensions_, which are opt-in non-standard language features. One of the effects of the specifying the Haskell 2010 language is that the language extensions listed https://downloads.haskell.org/~ghc/8.10.7/docs/html/users_guide/glasgow_exts.html#extension-Haskell2010[in this link] are enabled by GHC.

Additional language extensions can be (and typically are) specified by various mechanisms in the sub-project cabal configuration files or in the modules (i.e. source code files) themselves  https://kowainik.github.io/posts/extensions[as described here].

== Compiling asclepias projects

=== Compiling asclepias projects libraries and executables

The asclepias repository is organized using a multiple package setup. In more detail, some of the subdirectories of the repository such as `hasklepias-core`, `hasklepias-main`, etc. contain a cabal package. To start with, you can build all of the cabal projects in the repository using the following commands. Note that this will take 10 minutes or so to complete the first time that you do it. See `cabal build --help` for full details.
[source,shell]
----
# Build all of the projects. Add `-j` or `--jobs` to use all of your cores
cabal update
cabal build all

# Build projects one-at-a-time. This is useful when you are working on a particular
# project and don't want to compile everything. Add `-j` or `--jobs` to use all
# of your cores
cabal update
cabal build hasklepias-core  # or `hasklepias-main` or ...
----

=== Compiling asclepias projects tests

By default cabal doesn't compile the test suite for a given package so if you want to compile the tests you can use e.g. the `--enable-tests` option. (Note that it also doesn't compile benchmarking modules by default either.)
[source,shell]
----
cabal update
cabal build hasklepias-core --enable-tests  # or `hasklepias-main` or ...
----

== Setting up a development environment

=== Installing an editor

Haskell development is well-supported by many popular editors such as https://code.visualstudio.com[Visual Studio Code], https://www.sublimetext.com/[Sublime Text], https://www.vim.org/[vim] / https://neovim.io/[Neovim], https://atom.io/[Atom], https://www.gnu.org/software/emacs/[Emacs], and others. If you do not have a preexisting preference of editor then we recommend using Visual Studio Code to get started since it is easy to set up for Haskell development and is currently the most popular editor overall.

To see installation instructions for a given editor listed above, please visit the corresponding provided link. Note however that in the case of Emacs it is fairly common to use an Emacs distribution (basically a collection of packages bundled with base Emacs) to reduce the effort required to set up Emacs such as https://www.spacemacs.org/[Spacemacs], https://github.com/hlissner/doom-emacs[Doom Emacs], https://prelude.emacsredux.com/en/latest/[Emacs Prelude], or https://github.com/purcell/emacs.d[Purcell Emacs], among many others.

=== Installing the Haskell Language Server

The https://github.com/haskell/haskell-language-server[Haskell language server] (HLS) implements the https://microsoft.github.io/language-server-protocol/[Language Server Protocol] (LSP) for the Haskell language. It can be very useful for development when paired with an editor with support for LSP (such as one of the editors mentioned above) since it provides immediate feedback from the compiler, among other features.

You can use ghcup to install whatever its current recommended version of HLS is.
[source,shell]
----
ghcup install hls
----

=== Configuring your editor to utilize HLS

Please see  https://haskell-language-server.readthedocs.io/en/latest/configuration.html#configuring-your-editor[the HLS documentation] for instructions on how to configure your editor to utilize HLS.

==== A note on using HLS in multi-project repositories

Since the asclepias repository has a multiple project layout (i.e. hasklepias-core, hasklepias-main, etc.), it may not be obvious how to set up HLS. For example, should you run one server that serves all of the files across the various projects, or should you run one server per project?

To resolve this issue, the asclepias repository provides a file `hie.yaml` in the repository root that specifies the HLS configuration for all of the projects in the repository (see the https://github.com/haskell/hie-bios[hie-bios documentation] for details). As a result of this setup, you can run a single HLS server that will work correctly for all of the projects in the repository. If you are asked by your editor to specify what directory to start HLS in then you can use the repository root directory.

Note that some editors may automatically detect the hie-bios configuration setup in the repository and just "do the right thing." If you open a Haskell file in your editor and LSP seems to be working properly then you are probably good-to-go.

==== Troubleshooting HLS

If HLS ever stops working, you may need to clear the cache:

[source,shell]
----
rm -rf ~/.cache/hie-bios/dist-asclepias*
----

== Interactive usage of GHC

To run the examples interactively, open a ghci session with:

[source,shell]
----
cabal repl hasklepias-main:examples
----

In ghci you have access to all exposed functions in hasklepias, interval-algebra, and those in the examples folder.


== Linting and Formatting

The CI process checks that code in the repository is appropriately formatted and linted, using the https://hackage.haskell.org/package/brittany[`brittany`] and  https://github.com/ndmitchell/hlint[`hlint`] tools respectively. 

You can install these locally using (e.g.) `cabal`:

[source,shell]
----
cabal install brittany
cabal install hlint
----

Scripts are provided to format code locally with:

[source,shell]
----
./scripts/format.sh
----

or linted using: 

[source,shell]
----
./scripts/lint.sh
----

