
# Introductions

> "A case could be made to the effect that the typical history of a concept, whether it be 'chemical element', 'atom', 'the unconscious' or whatever, involves the initial emergence of the concept as a vague idea, followed by its gradual clarification as the theory in which it plays a part takes a more precise and coherent form" --A.F. Chalmers *What is This Thing Called Science*

Cohorts are a fundamental to many epidemiologic studies. However, converting source data such as insurance claims, electronic medical records, and case report forms into analysis-ready cohorts consumes an inordinate amount of resources in a research pipeline. The process may involve computationally-intensive transformations of source data into a common data model, preparing an analysis plan by researchers, and programmers who translate the analysis plan and wrangle data into analysis-ready files. 

```
Source data -- |ETL| --> Data model 
                            \
                             |Wrangle| --> Analysis files
                               /
Research Qs  -- |Write| --> SAP
```

The "wrangle" step is often the most challenging and largest bottleneck in terms of human resources. An analysis plan's natural language descriptions of the cohort creation algorithm must be translated into code. This step is prone to vague language by scientists and misinterpretations by programmers. Project Asclepias targets this step.

## Emerging, current approaches

* Original approach was floors of SAS programmers and double programming
* Describe various solutions such as [aetion](https://www.aetion.com/platform) and [ConceptQL](https://github.com/outcomesinsights/conceptql) (upon which Jigsaw is built) and [ODHSI](https://www.ohdsi.org/)'s [ATLAS](http://www.ohdsi.org/web/atlas/#/home) program
  
## Asceplias is different

Solutions such as ConceptQL and presumably others create a high level language for describing algorithms mapping tightly to a programming language, such as SQL. ConceptQL is indeed quite sophisticated and in many ways this project will appear similar. Still, Project Asclepias takes a somewhat different approach. Asclepias declares a cohort mathematically as composed of [algebraic data types](https://en.wikipedia.org/wiki/Algebraic_data_type) and functions that operate on these data types (think [category theory](https://www.youtube.com/watch?v=JH_Ou17_zyU)). Asclepias provides a rigorous framework for reasoning about, composing, and ultimately computing a cohort.

More thoughts:

* With a rigorous mathematical underpinning: 
     * software more straightforward to implement and test
     * a mapping to a more "expressive" language can be derived to be used in writing specifications

Moreover, with its mathematical foundation, Asclepias will be implemented using a [functional programming approach](https://en.wikipedia.org/wiki/Functional_programming): "[you don't tell the computer what to do as such but rather you tell it what stuff *is*.](http://learnyouahaskell.com/introduction#about-this-tutorial)"

## Towards flexible architectures

Many programming languages (R, python, scala, and so on) include functional programming concepts. This way of thinking about software design also lends itself to serverless architectures like [AWS Lambda](https://aws.amazon.com/lambda/). In fact, AWS Lambda gets its name from [lambda (or anonymous) functions](https://en.wikipedia.org/wiki/Anonymous_function) which come out of the [lambda calculus](https://en.wikipedia.org/wiki/Lambda_calculus) system, upon which *pure* functional languages are based.