:description: Documents the BuildNofX template
:source-highlighter: highlightjs

= `buildNofX`: Do N events satisfy a predicate X?

[TIP]
====
Use this template to create a `Definition` for a `Feature`
that answers the following question:

* [x] Do N events relating to the assessment interval in some way 
satisfy the given predicate?
====

== Usage and Examples

#TODO#

== Specialized Versions

`buildNofXBool`:: specialized to return `Bool`.

`buildNofXBinary`:: specialized to return a `stype` `Binary` value.

`buildNofXBinaryConcurBaseline`:: specialized to filter to events
that concur with an assessment interval.
created by `makeBaselineMeetsIndex` of a specified duration
and a provided predicate.

`buildNofTagSetBinaryConcurBaseline`:: specialized to filter to events
that concur with an assessment interval
created by `makeBaselineMeetsIndex` of a specified duration
and that have a given tag set.


== Source code

[%collapsible]
.View source code
====
[source,haskell]
----
include::BuildNofX.hs[tag=template0]
----
====