:sourceFile: DurationsWithMultipleConditions.hs 

= Find durations of time that satisfy multiple conditions

This example demonstrates

* [x] reasoning with the interval algebra
* [x] manipulating intervals
* [x] using a tag set to group events

In this example,
the goal is to write a function that,
given a pair of lists of tags and
an interval of time: 

* filters an input list of events to those that concur with the given interval.
Note that concur, in this context, means that the intervals are not disjoint.
* splits the events into those with the first tag and those with the second
* returns the start of the last event of the first tag set where
it occurs within +/- 3 time units of an event of the second tag set.

[TIP]
A function like this is useful
for defining an index event where the index 
needs to concur with a time window of other events.

[source,haskell]
----
include::{sourceFile}[tag=function]
----

Take the case that a subject has the following events,
and we want to know the first time a diagnosis
occurred within +/- 3 days of a procedure.
Our given interval, called `Baseline` here,
is (6, 15).
Below, we walk through the function step-by-by using this case.

----
      ---------                <- Baseline
    -                          <- [pr]
      -                        <- [pr]
          -                    <- [dx]
            -                  <- [pr]
            ----               <- [foo]
------------------------------
----

<1> Filter events to those concurring with the given interval.
+
----
      ---------                <- Baseline
      -                        <- [pr]
          -                    <- [dx]
            -                  <- [pr]
            ----               <- [foo]
------------------------------
----

<2> Form a pair of lists where the first element
has `t1` (dx in our example) event intervals and
the second has `t2` (pr in our example) event intervals.
Any events without tag `t1` or `t2` are dropped.
In the running example, 
the intervals of the events would make the 
following pair:
+
----
( [(10,11)] -- the dx event interval
, [(6,7), (12,13)] -- the pr event intervals
)
----

<3> Form a list of all (c1, c2) pairs of event intervals
from the previous step.
+
----
[ ( (10,11), (6,7) )
, ( (10,11), (12,13) ) 
]
----

<4> Expand the `c2` (pr) event intervals by +/- 3 units of time.
+
----
[ ( (10,11), (3,10) )
, ( (10,11), (9,16) ) 
]
----
Then, filter this list to include only instances 
where the `c1` (dx) interval concurs with a 'c2' interval.
+
----
[ ( (10,11), (9,16) ) ]
----

<5> Take `Just` the last element of the list, if it exists.
Otherwise, `Nothing`.

<6> If it exists, take the `begin` of the last `c1` interval.
In our example, this is `Just 10`.

Lastly, the example function can be lifted into a `Definition` using
the `define` function:

[source,haskell]
----
include::{sourceFile}[tag=definition]
----

