= Find the last event that occurs within a time window of other events

This example demonstrates:

* [x] the `+formMeetingSequence+` function from `+interval-algebra+`
* [x] handling a failure case
* [x] writing a function generic over both the concept and interval types

In this example,
the goal is to write a function that,
given a list of concepts,
converts a list of events into
a list of interval durations such that:

* the events with any of the given concepts are 
combined into a "meeting sequence";
* durations of events of the resulting sequence which have 
all of the given concepts are returned;
* but an empty result is treated as a failure.

[TIP]
A function like this could be useful
if you wanted to find the durations of time
when a subject was both hospitalized and on some medication.

[source,haskell]
----
include::Example2.hs[tag=function]
----

Take the case that a subject has the following events,
and we want to know the duration that a subject was 
both hospitalized and on antibiotics. 
Below, we walk through the function step-by-by using this case.

[source]
----
   --                          <- [Non-medication]
      ----                     <- [Hospitalized]
       --                      <- [Antibiotics]
            ----               <- [Antibiotics]
------------------------------
----

<1> Filter events to those that contain at least one
of the given concepts.
+
[source]
----
      ----                     <- [Hospitalized]
       --                      <- [Antibiotics]
            ----               <- [Antibiotics]
------------------------------
----

<2> Create a `+PairedInterval+` where the data is the concepts.
The `+getEvent+` function unwraps the `Event d c a` type to
a `+PairedInterval (Context d c) a+`.
The `+first+` function demonstrates the `+Bifunctor+` instance
of `+PairedInterval+`, 
applying `+getConcepts+` to tranform the type
`+PairedInterval (Context d c) a+` to
`+PairedInterval (Concepts c) a+`. 
<3> This step is important for the `+formMeetingSequence+` function,
as it requires the "data" part of the paired interval to be a `+Monoid+`.
`+Concepts+` are a `+Monoid+` by unioning the elements of two values.
<4> Form a sequence of intervals where one meets the next. 
The data of the running example would look like:
+
[source]
----
      -                        <- [Hospitalized]
       --                      <- [Hospitalized, Antibiotics]
         -                     <- [Hospitalized]
          --                   <- []
            ----               <- [Antibiotics]
------------------------------
----

<5> Filter to those intervals that have both of the given concepts.
Note that `hasAllConcepts` works here because 
`PairedInterval (Concepts c) a` is defined as an instance of the `HasConcepts`
typeclass in `event-data-theory`.
+
[source]
----
       --                      <- [Hospitalized, Antibiotics]
------------------------------
----

<6> Lastly, if the result of the previous step is empty,
we return a failure, i.e. a `+Left+` value of `FeatureData`.
Otherwise, we return the durations of any intervals,
as a successful `+Right+` value of `+FeatureData+`.

The `durationsOf` function can be lifted into a `Definition` 
using `defineA`:

[source,haskell]
----
include::Example2.hs[tag=definition]
----

<1> Create a function which takes a list of concepts and
<2> Returns a `Definition`