:sourceFile: HistoryOfEvent.hs

= Create a function for identifying whether a unit has a history of some event 

This example demonstrates:

* [x] a simple feature
* [x] writing a function in order to create multiple `+Feature+` definitions

A common question in epidemiologic studies is 
whether and when some event occurred.
In general, the event logic can be quite complicated,
but this example shows a function that 
identifies the whether an event of some given concepts occurred,
relative to a provided
xref:cohorts:page$examples.adoc[assessment interval].

The function is given here:

[source,haskell]
----
include::{sourceFile}[tag=function]
----

<1> The example events use `+Text+` as the type of concepts,
so the first argument is a list of `+Text+` values
that will be used to filter events.
<2> The return type is `+Maybe (Interval a)+`.
A value of `+Nothing+` indicates that no event of interest occurred.
If one or more events occur,
a value of `+Just < some interval >+` is the interval
of the last event. 
<3> The first step in the function is to filter events 
to those that contain at least one of the given concepts
and satisfies an interval relation relative to assessment interval.
For this example, we use the `+enclose+` relation,
meaning the event must not overlap either end of the assessment interval.
<4> The `+lastMay+` function returns the last element of a list,
if the last is not empty.
<5> Lastly, `+getInterval+` gets the interval component from the event. 
The `+fmap+` function is necessary to apply the function 
to a `+Maybe (Event Text ExampleModel a)+`.

With the `+makeHx+` function, 
we can create feature definitions:

[source,haskell]
----
include::{sourceFile}[tag=definition]
----

<1> Defines a feature that identifies whether a unit was
hit by a duck or struck by a duck.
<2> Defines a feature that identifies whether a unit was
hit by a macaw or struck by a macaw.