:sourceFile: TwoOutOneIn.hs

= Creating "Two outpatient or one inpatient" 

This example demonstrates:

* [x] a common feature used in studies of medical claims data
* [x] using a template to define a feature building function

This example defines a feature that indicates either:

* at least 1 event during the baseline interval has any of the `cpts1` concepts
* there are at least 2 events that have `cpts2` concepts which have at least
7 days between them during the baseline interval

[source,haskell]
----
include::{sourcefile}[tag=definition]
----

<1> The `twoOutOneIn` function returns a 
xref:theory$event-theory.adoc[`Definition`].
<2> We use the 
xref:features:page$templates.adoc[`buildNofXOrMofYWithGapBool`]
template function to build our definition. 
This function takes seven arguments.
<3> The first two are passed to the
xref:features:page$templates.adoc[`buildNofX`]
template.
The given arguments say that we're looking for *at least* `1` event
that contains one or more of the `inpatientConcepts`.
<4> The next three arguments are passed to the 
xref:features:page$templates.adoc[`buildNofXWithGap`]
template.
The given arguments say that we're looking for *at least* `1` gap 
between any pair of events (and thus at least 2 events)
that contains one or more of the `outpatientConcepts`.
<5> The last two arguments determine when the events 
must occur relative to the index event.
Here, the events must `concur` with a baseline 
xref:cohorts:page$examples.adoc[assessment interval].
